### ISSUE TITLE
Discrepency between /slacker list and /slacker gimme

### ISSUE THREAD

**Issue by grymmy** [hackclub/slacker#100]
Currently when I perform a `/slacker gimme sprig pulls`, I see the following:
![Screenshot 2023-12-12 at 2 54 57 PM](https://github.com/hackclub/slacker/assets/43505167/5c1e0358-d6d7-4b02-aa29-e94b35a7473f)
However, when I perform a `/slacker list sprig github`, I see the following:
![Screenshot 2023-12-12 at 2 55 34 PM](https://github.com/hackclub/slacker/assets/43505167/4512f742-9d4e-4741-a19c-d768d3126271)

these two #'s don't jive w/ each other

**Comment by faisalsayed10** [comment]
fixed
