### ISSUE TITLE
Follow-up functionality should mint new AI's instead of being a notification feature on existing AI's

### ISSUE THREAD

**Issue by grymmy** [hackclub/slacker#104]
It is my understanding that right now, when you "Follow up" on an item, it does not create a new AI, but instead saves some metadata (a reminder time) associated with the old AI.

I propose that a superior implementation would actually construct a whole new AI for follow-up items.  i.e., you would:
1. Click on "Follow up".
2. Pick a calendar date for follow-up
3. Enter some free-form text that would provide context for new new work.
4. Hit OK
This would end up creating a new AI that would immediately go into the work queue, but `/slacker gimme`'s would not return them until the specified date.  All filters and list counts should also not return these items either.

**Comment by faisalsayed10** [comment]
done
