### ISSUE TITLE
Slacker gimme should present a "gimme another" option after resolving AI

### ISSUE THREAD

**Issue by grymmy** [hackclub/slacker#108]
Since slack does not have command history, it is annoying to have to type out the slacker command repeatedly for every gimme.  Since the 'game loop' here is 99% of the time `gimme <x>, resolve, repeat`, it would be very helpful (and less prone to typos/errors) to automate the repeat step.

It would also be best for the 'repeat' button, whatever it is, to show you explicitly what cmd you'll be repeating (to help you keep context, especially if you walk away from the keyboard for a bathroom break)

**Comment by faisalsayed10** [comment]
done
