### ISSUE TITLE
Resolve option should become unavailable if you assign an issue to another person

### ISSUE THREAD

**Issue by grymmy** [hackclub/slacker#114]
I don't particularly care how this is solved, but it does seem like a mistake waiting to happen by allowing for this:
<img width="871" alt="Screenshot 2024-01-02 at 7 45 46 PM" src="https://github.com/hackclub/slacker/assets/43505167/f5ca5792-c29f-4fe1-a6d0-2ad3e1b261b3">
The resolve button still stays present after assignment (which is sort of a terminal operation, ending ones' responsibility and potential for needing to press 'resolve' in the future).  If mistakes happen, one can manually assign back.

**Comment by faisalsayed10** [comment]
implemented a fix
