### ISSUE TITLE
Optionally notify maintainers immediately whenever a PR is sent to their repo

### ISSUE THREAD

**Issue by grymmy** [hackclub/slacker#116]
I personally would love a dm whenever any pr is submitted against a repo I'm a maintainer of.  Ideally, this notification would also include a 'gimme' button that would acquire it if not already gimme'd by someone else.

**Comment by grymmy** [comment]
Some additional info here per our verbal chat:

1. this should only be for GH issues/PRs
2. it should not spam your "workspace" (DMs with the SLAcker app)
3. it should perhaps be an opt-in feature...?

**Comment by jdogcoder** [comment]
![CleanShot 2024-03-15 at 10 03 30@2x](https://github.com/hackclub/slacker/assets/65788728/d56b12ac-19a4-43aa-81f1-9361ae50c90d)

Closed 155 in favor of this issue.

**Comment by faisalsayed10** [comment]
@jdogcoder this has now been implemented, use `notify: []` array to add maintainers who need to be notified for each repo / channel / section (check `types.ts`)

**Comment by jdogcoder** [comment]
Thank you!
