### ISSUE TITLE
Slacker may not work correctly when using Slack web client

### ISSUE THREAD

**Issue by grymmy** [hackclub/slacker#117]
Lucas showed me over zoom that he was unable to successfully resolve gimme'd AI's when using the web client, but it worked on the native client.  We should probably audit the entirety of the web client to ensure all slacker functionality works properly.

**Comment by faisalsayed10** [comment]
i went through the entire flow of - list, gimme, me, resolve, assign. and it works flawlessly / exactly similar to how it works on the desktop client. the issue seems to be rather something else, which i will investigate in #118
