### ISSUE TITLE
/slacker gimme sprig games doesn't work for Lucas

### ISSUE THREAD

**Issue by grymmy** [hackclub/slacker#118]
I was on a zoom with Lucas and he showed me that `/slacker gimme sprig games` did not function as designed (it was unresponsive for him - never returned w/ an error or anything).  I then ran it on my account and it functioned as designed.

Do we need a new admin-only feature that would impersonate another user such that we could debug issues like this that seem account-specific?

**Comment by faisalsayed10** [comment]
determined what the issue was and pushed a fix

**Comment by faisalsayed10** [comment]
@LucasHT22 pls confirm and i can close this

**Comment by LucasHT22** [comment]
Looks everything ok! Thanks:)
