### ISSUE TITLE
Add command for showing all project responsibilities in summary manner

### ISSUE THREAD

**Issue by grymmy** [hackclub/slacker#12]
This would, for the target input user, display a summary of all responsibilities in whatever form is most effective and explanatory/practical/good.  For the current user only (not allowing for snooping on others), it could factor in current filter settings and other relevant status into its output to be helpful to the user - if not with this functionality, then "where" I guess would be my question...

I could imagine the slack command looking thusly: `/slacker whatsup (user)` <- parens indicating optional user param, defaulting to self, or the more boring `/slacker duties (user)`

**Comment by faisalsayed10** [comment]
done!
