### ISSUE TITLE
Slacker reclaimed an issue from me when it shouldn't

### ISSUE THREAD

**Issue by grymmy** [hackclub/slacker#124]
@sahitid [created a new repo request](https://github.com/hackclub/infra/issues/33) (defaulted to assign to me) two days ago, and  triaged it via slacker (I pinged sahiti to add more info, and assigned the gh issue to her as well as me) and resolved the slacker AI.  Slacker basically asked me "u want bug? NO BUG FOR U!", both of these messages were timestamped 7:00am this morning.

If we don't have any grafana coverage on clawback, we probably should - it would be good to know at what rate we send clawback warnings, the rate at which ppl answer those warnings, and the number of clawbacks that actually occur...

![Screenshot 2024-01-11 at 8 58 21 AM](https://github.com/hackclub/slacker/assets/43505167/159c2f98-f530-4db9-aee2-40f327ae6727)

**Comment by faisalsayed10** [comment]
should be fixed reopen if not
