### ISSUE TITLE
Do not request additional access than necessary

### ISSUE THREAD

**Issue by grymmy** [hackclub/slacker#13]
<img width="701" alt="Screenshot 2023-10-31 at 10 22 00 PM" src="https://github.com/hackclub/slacker/assets/43505167/b2505322-19ed-424f-8176-c5d564fc09d4">

This asks for access to perform actions on your behalf - per our discussion, we both think this is probably not necessary?  Please investigate and remove that if needed/is practical.

**Comment by faisalsayed10** [comment]
this should be fixed
