### ISSUE TITLE
Grouping should not be a global feature, but instead a property of specific slack resources

### ISSUE THREAD

**Issue by grymmy** [hackclub/slacker#134]
Specifically for Sprig, it is important for certain slack activity (such as the devices, devices-india, or games sections) not to be grouped.  Currently, the grouping configuration is at the top level as opposed to being defined w/ every resource:
<img width="318" alt="Screenshot 2024-01-29 at 2 32 16 PM" src="https://github.com/hackclub/slacker/assets/43505167/9de70f10-71d1-47df-a462-2b13c651e225">

**Comment by faisalsayed10** [comment]
grouping is now done at channel level. so grouping for device requests channel is disabled
