### ISSUE TITLE
Time to first response should really be time to first human response

### ISSUE THREAD

**Issue by grymmy** [hackclub/slacker#135]
Right now, it appears as though github response times don't filter out bot activity, resulting in an abnormally fast response time for bot-enabled repos.

**Comment by faisalsayed10** [comment]
fixed

**Comment by grymmy** [comment]
reopening this as I still observe 
<img width="597" alt="Screenshot 2024-02-15 at 4 28 46 PM" src="https://github.com/hackclub/slacker/assets/43505167/c424d9dc-cd65-4222-878a-76e45d33f5ac">

**Comment by faisalsayed10** [comment]
only onboard seems problematic regarding first response time. fixing that with #143
