### ISSUE TITLE
PR Assignments & Issue Status should sync with slacker assignments

### ISSUE THREAD

**Issue by jdogcoder** [hackclub/slacker#138]
If something is assigned in github, the slacker assignment should reflect that

**Comment by jdogcoder** [comment]
Same goes for if a PR or Issue is opened/closed

**Comment by grymmy** [comment]
So - issues and PRs are already closed on the slacker side when they close in GH - however, we do not want to mirror assignments in GH to slacker - slacker's job for GH issues generally ends with completion of triage (issue/PR has been tagged appropriately, is ready for work in GH, is perhaps assigned w/ a comment to someone who is blocking it proceeding w/ work).

As a result, I am closing this issue as wontfix.
