### ISSUE TITLE
"clear" slacker feed

### ISSUE THREAD

**Issue by jdogcoder** [hackclub/slacker#139]
The slacker dm can get very confusing with different messages from different times,

Could be cool to implement a "dashboard" thing like slashz, or have some way of keeping the feed clean

![CleanShot 2024-02-05 at 22 42 50@2x](https://github.com/hackclub/slacker/assets/65788728/268b3bd0-ae9d-42d7-a712-a9b9becb8ac5)

**Comment by JosiasAurel** [comment]
+1 would love to have this as well

**Comment by faisalsayed10** [comment]
done

**Comment by jdogcoder** [comment]
@faisalsayed10 not working for me
