### ISSUE TITLE
Add identifier to "follow up" button (and others?)

### ISSUE THREAD

**Issue by jdogcoder** [hackclub/slacker#142]
![CleanShot 2024-02-05 at 22 48 08@2x](https://github.com/hackclub/slacker/assets/65788728/b376cb97-38a2-4277-aa3e-30443fb8611a)

**Comment by grymmy** [comment]
@faisalsayed10 please add a comment here w/ what you plan on implementing to fix this

**Comment by faisalsayed10** [comment]
how about a small 20 character display of the text content?

**Comment by jdogcoder** [comment]
That would do it!
