### ISSUE TITLE
Configure ignores for users / channels

### ISSUE THREAD

**Issue by jdogcoder** [hackclub/slacker#143]
Would love to be able to specify users / channels or some combo of both to remidy things like this. 

![CleanShot 2024-02-05 at 22 49 18@2x](https://github.com/hackclub/slacker/assets/65788728/4378e4f3-3669-4925-a2bd-609a937dc428)

**Comment by jdogcoder** [comment]
Something like adding a maintainer wouln't work because the bot also sends the requests (just in a different channel)

**Comment by jdogcoder** [comment]
This issue might be too specific to one project though.

**Comment by grymmy** [comment]
this lgtm

**Comment by maxwofford** [comment]
This just came up for welcome committee -- tasks should only be created for posts by the @/toriel bot instead of regular messages.

(Happy to break this into a separate issue if you want)

**Comment by faisalsayed10** [comment]
closing for now. out of scope for slacker. messages from the maintainers of a project don't cause new AIs.
