### ISSUE TITLE
Detect github action failures

### ISSUE THREAD

**Issue by grymmy** [hackclub/slacker#153]
I'm thinking slacker might be a reasonable place to emit telemetry on github action failures such that we could then add alerts when, for instance, dns fails octodns deployments.

Can we a) investigate whether slacker is actually a good place for this (there might be alternatives) and b) if so add this telemetry + an alert or two in grafana, covering this?

**Comment by faisalsayed10** [comment]
added logs for now, will see how the logs look like and then i'll integrate with grafana in the future
https://github.com/hackclub/slacker/commit/5ca9584f234c79746427a862e7136a1c8cd4d975

**Comment by faisalsayed10** [comment]
closing for now since i dont see a usecase for this in slacker
