### ISSUE TITLE
Ticket auto assignment

### ISSUE THREAD

**Issue by jdogcoder** [hackclub/slacker#155]
For some teams, in my mind it makes sense to be able to enable "auto assignment" in the project config. This assigns tickets to users automatically with assignment to make it quick to get action foe those of us who don't regularly `gimme` in our spare time :) 

Having this in project config allows opt-in as this is not something every team would want I imagine.

Ideally a robust system would allow assignment of users to specific filters/categories to allow for proper assignment, but I'd be happy with just a auto assign! 

My vision for this is very similar to how assignment for reviews of PRs works with codeowners on Github, incase inspiration is needed.

**Comment by grymmy** [comment]
What use case would this be fixing that is broken right now?  TBH, if we are using slacker as it was intended, part of triage would be (potentially) assigning issues to yourself, or others, in github.  We could for instance make the process of doing that easier via some new slacker feature.

TBH, I am a bit of a believer in processes that a) enforce proper triage b) have assignment be valid only when you're *actually* working on something.  If you're sitting on 50 issues, that is not really helpful and also dissuades others from picking up work that _you're not actually working on_.  Github already does provide some [auto-assignment functionality when it comes to code reviews](https://docs.github.com/en/organizations/organizing-members-into-teams/managing-code-review-settings-for-your-team#about-auto-assignment) that is handled separately from the current assignee...

Separately - I am not sure such a robust system (true auto-assignment based on smarts) is possible to implement in a sane/reasonable way.

**Comment by faisalsayed10** [comment]
I think it's less of fixing something right now but more of a quality of life improvement for certain projects. For example, Jasper needs this for the #leaders channel, and max had previously mentioned that he needs onboard-grant-requests to be auto-assigned to him because he's the only one working on it.

so we could maybe implement a default maintainers list on channel / repo level

**Comment by grymmy** [comment]
1) Why does jasper need this for #leaders?

2) if only one person is working on a project, why is it extremely important to assign anyone to anything at all?

**Comment by faisalsayed10** [comment]
cc: @jdogcoder

**Comment by jdogcoder** [comment]
Typing......

**Comment by jdogcoder** [comment]
To answer 2 first, for something like that use case not having to do perpetual gimme's, and just get a notif that you were auto assigned the slacker ticket, allows for a much more seamless flow in my mind, but you would have to see @maxwofford's thoughts. This is a use case I could see for myself as I am handling most of pizza grant requests right now, so auto assigning those to me, is just less gimmes to run.

In terms of my stuffs, as @faisalsayed10 said, it is definitely more of a QOL and less of something that is broken / needs fixing. For the leaders project, any of us can work on any of the tickets for the most part, so having some sort of round robin assignment would help divy and assign the tickets to us quickly so we could use that to drive our action. 

Ultimately this comes down to programmers (particularly me) being lazy, but also wanting to optimize workflows.

**Comment by jdogcoder** [comment]
Closing in favor of #116 as proposed and agreed upon by @grymmy, @faisalsayed10, and I.

**Comment by jdogcoder** [comment]
![CleanShot 2024-03-15 at 10 03 30@2x](https://github.com/hackclub/slacker/assets/65788728/b77351ef-7d4f-4a6c-9add-ffc7fc6deb95)
