### ISSUE TITLE
No feedback when attempting to resolve github issue

### ISSUE THREAD

**Issue by grymmy** [hackclub/slacker#16]
Pressing 'resolve' on this issue results in no confirmation from slacker that the work was completed (unlike slack, where I get a msg confirming something happened)...  results in me assuming it broke

![Screenshot 2023-11-02 at 9 29 31 AM](https://github.com/hackclub/slacker/assets/43505167/cf5ff7b7-7147-4bff-a404-8ec1a57fa87f)

**Comment by faisalsayed10** [comment]
fixed
