### ISSUE TITLE
Define slacker users in hard-coded config file, and use references to these users within project definitions

### ISSUE THREAD

**Issue by grymmy** [hackclub/slacker#24]
This may change in the future, but we want Slacker users (both high-level names to be used within slacker configs, and slack/github info) defined in one centralized config file.

All users within project configuration files should use the high-level, human-readable names as opposed to slack/github IDs.

It may make sense to make this more database-driven w/ associated web UI in the future...

**Comment by faisalsayed10** [comment]
done
