### ISSUE TITLE
Issue closed on GH still shows up as unassigned AI in slacker

### ISSUE THREAD

**Issue by grymmy** [hackclub/slacker#27]
https://github.com/hackclub/scrappy/issues/110 - Closed last week

In slacker today:
![Screenshot 2023-11-08 at 12 52 44 PM](https://github.com/hackclub/slacker/assets/43505167/0f668b37-f0c6-4d3a-b82c-39f7496e28b9)

**Comment by faisalsayed10** [comment]
fixed
