### ISSUE TITLE
Make snooze default to the next business day, 7am EST

### ISSUE THREAD

**Issue by grymmy** [hackclub/slacker#44]
In my experience I never snooze for less than one business day - I think it would be a good default, and would save many repetitive unnecessary clicks w this logic.

**Comment by faisalsayed10** [comment]
should be fixed

**Comment by grymmy** [comment]
This does not respect next business day by default in UI - evidence:
![Screenshot 2023-11-17 at 10 21 36 AM](https://github.com/hackclub/slacker/assets/43505167/fd7a13ad-d50f-43b9-b9f3-1f6f3f61236d)

**Comment by faisalsayed10** [comment]
fixed now
<img width="736" alt="image" src="https://github.com/hackclub/slacker/assets/36627266/2361f5e8-f546-4b36-9dfc-4125cf6b7c9e">
