### ISSUE TITLE
Add delimiter of some kind (horizontal rule?) in between each AI

### ISSUE THREAD

**Issue by grymmy** [hackclub/slacker#46]
The UI of the multiple AIs blend together a bit as seen here:
<img width="256" alt="Screenshot 2023-11-10 at 4 36 49 PM" src="https://github.com/hackclub/slacker/assets/43505167/4fd5ccae-4aa0-459d-bb7b-9bb7c62f8d24">

It would be better to clearly separate them via some sort of hr.

**Comment by faisalsayed10** [comment]
added a divider
