### ISSUE TITLE
Work items are repeated resulting in unnecessary work

### ISSUE THREAD

**Issue by grymmy** [hackclub/slacker#47]
In attempting to work through the sprig queue, there are many repeated work items.  Items that we hit 'resolve' on should not show up in subsequent calls to /slacker list.

Proof that this happened:
<img width="512" alt="Screenshot 2023-11-10 at 4 53 57 PM" src="https://github.com/hackclub/slacker/assets/43505167/23729e08-3894-429a-9590-689c4387a3a5">

**Comment by grymmy** [comment]
Please prioritize this one, it's especially bad and distractive/time-wasting

**Comment by faisalsayed10** [comment]
should be fixed for consecutive resolutions, please reopen if it happens again
