### ISSUE TITLE
Slacker should be able to filter by resource type

### ISSUE THREAD

**Issue by grymmy** [hackclub/slacker#49]
Sometimes I want to be in community-support mode and focus on Slack work, sometimes I want to be in white-hat PR review mode, and sometimes I want to pick up a trash bag and clean up some bug reports or feature requests.

Very broadly, slacker should respect the type of work that people desire to do (or review)....  filter types at this point could be slack, issues, or code?  Use cases that should respect this:

I want a new piece of work `of worktype`
I want to see work on this `project` `of worktype`
I want to see analytics on `worktype`

**Comment by faisalsayed10** [comment]
slacker supports this now
