### ISSUE TITLE
Define slacker analytics ES document schema

### ISSUE THREAD

**Issue by grymmy** [hackclub/slacker#58]
Add a comment here to this issue with the specific schema(s) we want to store in ES for slacker analytics purposes.

**Comment by grymmy** [comment]
The document should look as such:

```
{
  "username": "graham",
  "state": "open|triaged|resolved",
  "project": "projectName",
  "actionItemType": "issue|pr|message",
  "createdTime": "timestamp",
  "firstResponseTime": "timestamp"|null,
  "lastModifiedTime": "timestamp",
  "timesSnoozed": 1,
  "timesReopened": 0,
  "timesResolved": 1,
  "timesCommented":5,
  "actors": ["graham", "fayd"],
}
```

There should be a 1:1 mapping between action items and their corresponding documents indexed in elasticsearch (i.e., the documents above should be indexed using action item unique identifiers).

**Comment by faisalsayed10** [comment]
this is completed
