### ISSUE TITLE
Action item assigned to undefined user

### ISSUE THREAD

**Issue by grymmy** [hackclub/slacker#64]
I experienced an issue with action-item ID cloqc7piy02faxy14ky0iys8i - I fiddled with the AI's assignee field a bit to play w/ the assigning feature, and then ended up re-selecting myself as the assignee, and then received the following message:

![Screenshot 2023-11-15 at 11 40 56 AM](https://github.com/hackclub/slacker/assets/43505167/100ceb15-acdf-4722-a53e-887e198ac837)

The following is the user that it got assigned to
![Screenshot 2023-11-15 at 11 41 48 AM](https://github.com/hackclub/slacker/assets/43505167/0a57f064-ce74-4b7a-9821-e89d3b415529)

**Comment by faisalsayed10** [comment]
should be fixed when i push
