### ISSUE TITLE
Action items need to show what project they are associated with

### ISSUE THREAD

**Issue by grymmy** [hackclub/slacker#69]
When working on multiple projects, it is impossible to discern which AIs are relating to which projects...  Yes I can figure it out by squinting my eyes carefully and looking at the text and other data, but it would ease the mental load of the user to just be explicit...
  Ex:
<img width="761" alt="Screenshot 2023-11-16 at 4 27 48 PM" src="https://github.com/hackclub/slacker/assets/43505167/fe4f0dde-5b1f-4e5b-ad56-f0609a4d7a3b">

**Comment by faisalsayed10** [comment]
done
