### ISSUE TITLE
Implement GH issue clawback

### ISSUE THREAD

**Issue by grymmy** [hackclub/slacker#71]
1. After initial gh issue assignment, we will give a 5 day grace period for GH issues to be worked on.  
2. After 5 days, we will send a slack message to the user asking if they'd like to continue working on it.  If they state yes, give them another 5 days.  If they state no, unassign the issue in github and notify user that this happened via slack.  If they do not respond, clawback after 2 more days (also warn them of this in the 5 day msg) (and notify the user it happened via slack).

**Comment by faisalsayed10** [comment]
- a reminder system where slacker would DM and have ppl confirm "Is this being worked on?  is anyone waiting on you for this (if not plz assign it away!)
- some sort of criteria to reopen AIs
