### ISSUE TITLE
Support changing your project filtering settings at runtime

### ISSUE THREAD

**Issue by grymmy** [hackclub/slacker#8]
While we organize people into projects via configuration, users themselves might want to filter (focus) their attention on specific projects or resources.  I could imagine this being implemented as such:

`/slacker filter projectname1,projectname2`

and to remove all filtering
`/slacker filter none`

**Comment by ivoinestrachan** [comment]
can i be assign to this

**Comment by faisalsayed10** [comment]
@grymmy should this not be inputted into `/slacker list <project> <filter>`? because if we have a `/slacker filter` command, we'll also have to store their filter config somewhere. thoughts?
