### ISSUE TITLE
Support assigning work items to specific users

### ISSUE THREAD

**Issue by grymmy** [hackclub/slacker#9]
There may be cases where someone does not have sufficient skills (or time, or whatever) to resolve a work item.  For these cases, you should be able to assign one of your work items to another specific individual - for instance:

`/slacker assign <workitemid> <username/email?>`

**Comment by faisalsayed10** [comment]
`/slacker me` command that would get one work item and auto-assign it to the invoker for them to work on it. they wont get a new work item unless to either assign it further, snooze or resolve

**Comment by faisalsayed10** [comment]
show who the assignee is in the `list` command

**Comment by faisalsayed10** [comment]
done
