### ISSUE TITLE
Empty items show up in slacker analytics

### ISSUE THREAD

**Issue by grymmy** [hackclub/slacker#93]
What are these (empty) entries?

![Screenshot 2023-12-07 at 10 12 16 AM](https://github.com/hackclub/slacker/assets/43505167/ae541c26-5aea-47e2-acbb-ee72af20e7b9)

**Comment by faisalsayed10** [comment]
those were action items that accidentally got created cuz they weren't within a project. i've fixed the code and it should not happen from now on. but im unable to delete the current ones...
